apiVersion: batch/v1

kind: CronJob

metadata:

  name: my-batch-job

spec:

  schedule: '*/2 * * * *'

  jobTemplate:

    spec:

      template:

        spec:

          affinity:

            nodeAffinity:

              requiredDuringSchedulingIgnoredDuringExecution:

                nodeSelectorTerms:

                  - matchFields:

                      - key: metadata.name

                        operator: In

                        values:

                          - i-00b815edea478d865

          containers:

            - name: my-batch-container

              image: 'kaushikseetharam/kubernetes_lab:v.0.3'

          restartPolicy: OnFailure
