apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-batch-job
spec:
  schedule: '*/2 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-batch-container
              image: 'kaushikseetharam/kubernetes_lab:v.0.1'
          restartPolicy: OnFailure
